//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Quan_Ly_Nha_Hang
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public string ma_km { get; set; }
        public string ten_km { get; set; }
        public Nullable<int> yeu_cau { get; set; }
        public Nullable<int> tien_giam { get; set; }
    }
}
